extern void (APIENTRY* GL_Accum)(GLenum op, GLfloat value);
extern void (APIENTRY* GL_AlphaFunc)(GLenum func, GLclampf ref);
extern GLboolean (APIENTRY* GL_AreTexturesResident)(GLsizei n, const GLuint *textures, GLboolean *residences);
extern void (APIENTRY* GL_ArrayElement)(GLint i);
extern void (APIENTRY* GL_Begin)(GLenum mode);
extern void (APIENTRY* GL_BindTexture)(GLenum target, GLuint texture);
extern void (APIENTRY* GL_Bitmap)(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
extern void (APIENTRY* GL_BlendFunc)(GLenum sfactor, GLenum dfactor);
extern void (APIENTRY* GL_CallList)(GLuint list);
extern void (APIENTRY* GL_CallLists)(GLsizei n, GLenum type, const GLvoid *lists);
extern void (APIENTRY* GL_Clear)(GLbitfield mask);
extern void (APIENTRY* GL_ClearAccum)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void (APIENTRY* GL_ClearColor)(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
extern void (APIENTRY* GL_ClearDepth)(GLclampd depth);
extern void (APIENTRY* GL_ClearIndex)(GLfloat c);
extern void (APIENTRY* GL_ClearStencil)(GLint s);
extern void (APIENTRY* GL_ClipPlane)(GLenum plane, const GLdouble *equation);
extern void (APIENTRY* GL_Color3b)(GLbyte red, GLbyte green, GLbyte blue);
extern void (APIENTRY* GL_Color3bv)(const GLbyte *v);
extern void (APIENTRY* GL_Color3d)(GLdouble red, GLdouble green, GLdouble blue);
extern void (APIENTRY* GL_Color3dv)(const GLdouble *v);
extern void (APIENTRY* GL_Color3f)(GLfloat red, GLfloat green, GLfloat blue);
extern void (APIENTRY* GL_Color3fv)(const GLfloat *v);
extern void (APIENTRY* GL_Color3i)(GLint red, GLint green, GLint blue);
extern void (APIENTRY* GL_Color3iv)(const GLint *v);
extern void (APIENTRY* GL_Color3s)(GLshort red, GLshort green, GLshort blue);
extern void (APIENTRY* GL_Color3sv)(const GLshort *v);
extern void (APIENTRY* GL_Color3ub)(GLubyte red, GLubyte green, GLubyte blue);
extern void (APIENTRY* GL_Color3ubv)(const GLubyte *v);
extern void (APIENTRY* GL_Color3ui)(GLuint red, GLuint green, GLuint blue);
extern void (APIENTRY* GL_Color3uiv)(const GLuint *v);
extern void (APIENTRY* GL_Color3us)(GLushort red, GLushort green, GLushort blue);
extern void (APIENTRY* GL_Color3usv)(const GLushort *v);
extern void (APIENTRY* GL_Color4b)(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
extern void (APIENTRY* GL_Color4bv)(const GLbyte *v);
extern void (APIENTRY* GL_Color4d)(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
extern void (APIENTRY* GL_Color4dv)(const GLdouble *v);
extern void (APIENTRY* GL_Color4f)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void (APIENTRY* GL_Color4fv)(const GLfloat *v);
extern void (APIENTRY* GL_Color4i)(GLint red, GLint green, GLint blue, GLint alpha);
extern void (APIENTRY* GL_Color4iv)(const GLint *v);
extern void (APIENTRY* GL_Color4s)(GLshort red, GLshort green, GLshort blue, GLshort alpha);
extern void (APIENTRY* GL_Color4sv)(const GLshort *v);
extern void (APIENTRY* GL_Color4ub)(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
extern void (APIENTRY* GL_Color4ubv)(const GLubyte *v);
extern void (APIENTRY* GL_Color4ui)(GLuint red, GLuint green, GLuint blue, GLuint alpha);
extern void (APIENTRY* GL_Color4uiv)(const GLuint *v);
extern void (APIENTRY* GL_Color4us)(GLushort red, GLushort green, GLushort blue, GLushort alpha);
extern void (APIENTRY* GL_Color4usv)(const GLushort *v);
extern void (APIENTRY* GL_ColorMask)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
extern void (APIENTRY* GL_ColorMaterial)(GLenum face, GLenum mode);
extern void (APIENTRY* GL_ColorPointer)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
extern void (APIENTRY* GL_CopyPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
extern void (APIENTRY* GL_CopyTexImage1D)(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border);
extern void (APIENTRY* GL_CopyTexImage2D)(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
extern void (APIENTRY* GL_CopyTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
extern void (APIENTRY* GL_CopyTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern void (APIENTRY* GL_CullFace)(GLenum mode);
extern void (APIENTRY* GL_DeleteLists)(GLuint list, GLsizei range);
extern void (APIENTRY* GL_DeleteTextures)(GLsizei n, const GLuint *textures);
extern void (APIENTRY* GL_DepthFunc)(GLenum func);
extern void (APIENTRY* GL_DepthMask)(GLboolean flag);
extern void (APIENTRY* GL_DepthRange)(GLclampd zNear, GLclampd zFar);
extern void (APIENTRY* GL_Disable)(GLenum cap);
extern void (APIENTRY* GL_DisableClientState)(GLenum array);
extern void (APIENTRY* GL_DrawArrays)(GLenum mode, GLint first, GLsizei count);
extern void (APIENTRY* GL_DrawBuffer)(GLenum mode);
extern void (APIENTRY* GL_DrawElements)(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
extern void (APIENTRY* GL_DrawPixels)(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
extern void (APIENTRY* GL_EdgeFlag)(GLboolean flag);
extern void (APIENTRY* GL_EdgeFlagPointer)(GLsizei stride, const GLvoid *pointer);
extern void (APIENTRY* GL_EdgeFlagv)(const GLboolean *flag);
extern void (APIENTRY* GL_Enable)(GLenum cap);
extern void (APIENTRY* GL_EnableClientState)(GLenum array);
extern void (APIENTRY* GL_End)(void);
extern void (APIENTRY* GL_EndList)(void);
extern void (APIENTRY* GL_EvalCoord1d)(GLdouble u);
extern void (APIENTRY* GL_EvalCoord1dv)(const GLdouble *u);
extern void (APIENTRY* GL_EvalCoord1f)(GLfloat u);
extern void (APIENTRY* GL_EvalCoord1fv)(const GLfloat *u);
extern void (APIENTRY* GL_EvalCoord2d)(GLdouble u, GLdouble v);
extern void (APIENTRY* GL_EvalCoord2dv)(const GLdouble *u);
extern void (APIENTRY* GL_EvalCoord2f)(GLfloat u, GLfloat v);
extern void (APIENTRY* GL_EvalCoord2fv)(const GLfloat *u);
extern void (APIENTRY* GL_EvalMesh1)(GLenum mode, GLint i1, GLint i2);
extern void (APIENTRY* GL_EvalMesh2)(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
extern void (APIENTRY* GL_EvalPoint1)(GLint i);
extern void (APIENTRY* GL_EvalPoint2)(GLint i, GLint j);
extern void (APIENTRY* GL_FeedbackBuffer)(GLsizei size, GLenum type, GLfloat *buffer);
extern void (APIENTRY* GL_Finish)(void);
extern void (APIENTRY* GL_Flush)(void);
extern void (APIENTRY* GL_Fogf)(GLenum pname, GLfloat param);
extern void (APIENTRY* GL_Fogfv)(GLenum pname, const GLfloat *params);
extern void (APIENTRY* GL_Fogi)(GLenum pname, GLint param);
extern void (APIENTRY* GL_Fogiv)(GLenum pname, const GLint *params);
extern void (APIENTRY* GL_FrontFace)(GLenum mode);
extern void (APIENTRY* GL_Frustum)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
extern GLuint (APIENTRY* GL_GenLists)(GLsizei range);
extern void (APIENTRY* GL_GenTextures)(GLsizei n, GLuint *textures);
extern void (APIENTRY* GL_GetBooleanv)(GLenum pname, GLboolean *params);
extern void (APIENTRY* GL_GetClipPlane)(GLenum plane, GLdouble *equation);
extern void (APIENTRY* GL_GetDoublev)(GLenum pname, GLdouble *params);
extern GLenum (APIENTRY* GL_GetError)(void);
extern void (APIENTRY* GL_GetFloatv)(GLenum pname, GLfloat *params);
extern void (APIENTRY* GL_GetIntegerv)(GLenum pname, GLint *params);
extern void (APIENTRY* GL_GetLightfv)(GLenum light, GLenum pname, GLfloat *params);
extern void (APIENTRY* GL_GetLightiv)(GLenum light, GLenum pname, GLint *params);
extern void (APIENTRY* GL_GetMapdv)(GLenum target, GLenum query, GLdouble *v);
extern void (APIENTRY* GL_GetMapfv)(GLenum target, GLenum query, GLfloat *v);
extern void (APIENTRY* GL_GetMapiv)(GLenum target, GLenum query, GLint *v);
extern void (APIENTRY* GL_GetMaterialfv)(GLenum face, GLenum pname, GLfloat *params);
extern void (APIENTRY* GL_GetMaterialiv)(GLenum face, GLenum pname, GLint *params);
extern void (APIENTRY* GL_GetPixelMapfv)(GLenum map, GLfloat *values);
extern void (APIENTRY* GL_GetPixelMapuiv)(GLenum map, GLuint *values);
extern void (APIENTRY* GL_GetPixelMapusv)(GLenum map, GLushort *values);
extern void (APIENTRY* GL_GetPointerv)(GLenum pname, GLvoid* *params);
extern void (APIENTRY* GL_GetPolygonStipple)(GLubyte *mask);
extern const GLubyte * (APIENTRY* GL_GetString)(GLenum name);
extern void (APIENTRY* GL_GetTexEnvfv)(GLenum target, GLenum pname, GLfloat *params);
extern void (APIENTRY* GL_GetTexEnviv)(GLenum target, GLenum pname, GLint *params);
extern void (APIENTRY* GL_GetTexGendv)(GLenum coord, GLenum pname, GLdouble *params);
extern void (APIENTRY* GL_GetTexGenfv)(GLenum coord, GLenum pname, GLfloat *params);
extern void (APIENTRY* GL_GetTexGeniv)(GLenum coord, GLenum pname, GLint *params);
extern void (APIENTRY* GL_GetTexImage)(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels);
extern void (APIENTRY* GL_GetTexLevelParameterfv)(GLenum target, GLint level, GLenum pname, GLfloat *params);
extern void (APIENTRY* GL_GetTexLevelParameteriv)(GLenum target, GLint level, GLenum pname, GLint *params);
extern void (APIENTRY* GL_GetTexParameterfv)(GLenum target, GLenum pname, GLfloat *params);
extern void (APIENTRY* GL_GetTexParameteriv)(GLenum target, GLenum pname, GLint *params);
extern void (APIENTRY* GL_Hint)(GLenum target, GLenum mode);
extern void (APIENTRY* GL_IndexMask)(GLuint mask);
extern void (APIENTRY* GL_IndexPointer)(GLenum type, GLsizei stride, const GLvoid *pointer);
extern void (APIENTRY* GL_Indexd)(GLdouble c);
extern void (APIENTRY* GL_Indexdv)(const GLdouble *c);
extern void (APIENTRY* GL_Indexf)(GLfloat c);
extern void (APIENTRY* GL_Indexfv)(const GLfloat *c);
extern void (APIENTRY* GL_Indexi)(GLint c);
extern void (APIENTRY* GL_Indexiv)(const GLint *c);
extern void (APIENTRY* GL_Indexs)(GLshort c);
extern void (APIENTRY* GL_Indexsv)(const GLshort *c);
extern void (APIENTRY* GL_Indexub)(GLubyte c);
extern void (APIENTRY* GL_Indexubv)(const GLubyte *c);
extern void (APIENTRY* GL_InitNames)(void);
extern void (APIENTRY* GL_InterleavedArrays)(GLenum format, GLsizei stride, const GLvoid *pointer);
extern GLboolean (APIENTRY* GL_IsEnabled)(GLenum cap);
extern GLboolean (APIENTRY* GL_IsList)(GLuint list);
extern GLboolean (APIENTRY* GL_IsTexture)(GLuint texture);
extern void (APIENTRY* GL_LightModelf)(GLenum pname, GLfloat param);
extern void (APIENTRY* GL_LightModelfv)(GLenum pname, const GLfloat *params);
extern void (APIENTRY* GL_LightModeli)(GLenum pname, GLint param);
extern void (APIENTRY* GL_LightModeliv)(GLenum pname, const GLint *params);
extern void (APIENTRY* GL_Lightf)(GLenum light, GLenum pname, GLfloat param);
extern void (APIENTRY* GL_Lightfv)(GLenum light, GLenum pname, const GLfloat *params);
extern void (APIENTRY* GL_Lighti)(GLenum light, GLenum pname, GLint param);
extern void (APIENTRY* GL_Lightiv)(GLenum light, GLenum pname, const GLint *params);
extern void (APIENTRY* GL_LineStipple)(GLint factor, GLushort pattern);
extern void (APIENTRY* GL_LineWidth)(GLfloat width);
extern void (APIENTRY* GL_ListBase)(GLuint base);
extern void (APIENTRY* GL_LoadIdentity)(void);
extern void (APIENTRY* GL_LoadMatrixd)(const GLdouble *m);
extern void (APIENTRY* GL_LoadMatrixf)(const GLfloat *m);
extern void (APIENTRY* GL_LoadName)(GLuint name);
extern void (APIENTRY* GL_LogicOp)(GLenum opcode);
extern void (APIENTRY* GL_Map1d)(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
extern void (APIENTRY* GL_Map1f)(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
extern void (APIENTRY* GL_Map2d)(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
extern void (APIENTRY* GL_Map2f)(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
extern void (APIENTRY* GL_MapGrid1d)(GLint un, GLdouble u1, GLdouble u2);
extern void (APIENTRY* GL_MapGrid1f)(GLint un, GLfloat u1, GLfloat u2);
extern void (APIENTRY* GL_MapGrid2d)(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
extern void (APIENTRY* GL_MapGrid2f)(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
extern void (APIENTRY* GL_Materialf)(GLenum face, GLenum pname, GLfloat param);
extern void (APIENTRY* GL_Materialfv)(GLenum face, GLenum pname, const GLfloat *params);
extern void (APIENTRY* GL_Materiali)(GLenum face, GLenum pname, GLint param);
extern void (APIENTRY* GL_Materialiv)(GLenum face, GLenum pname, const GLint *params);
extern void (APIENTRY* GL_MatrixMode)(GLenum mode);
extern void (APIENTRY* GL_MultMatrixd)(const GLdouble *m);
extern void (APIENTRY* GL_MultMatrixf)(const GLfloat *m);
extern void (APIENTRY* GL_NewList)(GLuint list, GLenum mode);
extern void (APIENTRY* GL_Normal3b)(GLbyte nx, GLbyte ny, GLbyte nz);
extern void (APIENTRY* GL_Normal3bv)(const GLbyte *v);
extern void (APIENTRY* GL_Normal3d)(GLdouble nx, GLdouble ny, GLdouble nz);
extern void (APIENTRY* GL_Normal3dv)(const GLdouble *v);
extern void (APIENTRY* GL_Normal3f)(GLfloat nx, GLfloat ny, GLfloat nz);
extern void (APIENTRY* GL_Normal3fv)(const GLfloat *v);
extern void (APIENTRY* GL_Normal3i)(GLint nx, GLint ny, GLint nz);
extern void (APIENTRY* GL_Normal3iv)(const GLint *v);
extern void (APIENTRY* GL_Normal3s)(GLshort nx, GLshort ny, GLshort nz);
extern void (APIENTRY* GL_Normal3sv)(const GLshort *v);
extern void (APIENTRY* GL_NormalPointer)(GLenum type, GLsizei stride, const GLvoid *pointer);
extern void (APIENTRY* GL_Ortho)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
extern void (APIENTRY* GL_PassThrough)(GLfloat token);
extern void (APIENTRY* GL_PixelMapfv)(GLenum map, GLsizei mapsize, const GLfloat *values);
extern void (APIENTRY* GL_PixelMapuiv)(GLenum map, GLsizei mapsize, const GLuint *values);
extern void (APIENTRY* GL_PixelMapusv)(GLenum map, GLsizei mapsize, const GLushort *values);
extern void (APIENTRY* GL_PixelStoref)(GLenum pname, GLfloat param);
extern void (APIENTRY* GL_PixelStorei)(GLenum pname, GLint param);
extern void (APIENTRY* GL_PixelTransferf)(GLenum pname, GLfloat param);
extern void (APIENTRY* GL_PixelTransferi)(GLenum pname, GLint param);
extern void (APIENTRY* GL_PixelZoom)(GLfloat xfactor, GLfloat yfactor);
extern void (APIENTRY* GL_PointSize)(GLfloat size);
extern void (APIENTRY* GL_PolygonMode)(GLenum face, GLenum mode);
extern void (APIENTRY* GL_PolygonOffset)(GLfloat factor, GLfloat units);
extern void (APIENTRY* GL_PolygonStipple)(const GLubyte *mask);
extern void (APIENTRY* GL_PopAttrib)(void);
extern void (APIENTRY* GL_PopClientAttrib)(void);
extern void (APIENTRY* GL_PopMatrix)(void);
extern void (APIENTRY* GL_PopName)(void);
extern void (APIENTRY* GL_PrioritizeTextures)(GLsizei n, const GLuint *textures, const GLclampf *priorities);
extern void (APIENTRY* GL_PushAttrib)(GLbitfield mask);
extern void (APIENTRY* GL_PushClientAttrib)(GLbitfield mask);
extern void (APIENTRY* GL_PushMatrix)(void);
extern void (APIENTRY* GL_PushName)(GLuint name);
extern void (APIENTRY* GL_RasterPos2d)(GLdouble x, GLdouble y);
extern void (APIENTRY* GL_RasterPos2dv)(const GLdouble *v);
extern void (APIENTRY* GL_RasterPos2f)(GLfloat x, GLfloat y);
extern void (APIENTRY* GL_RasterPos2fv)(const GLfloat *v);
extern void (APIENTRY* GL_RasterPos2i)(GLint x, GLint y);
extern void (APIENTRY* GL_RasterPos2iv)(const GLint *v);
extern void (APIENTRY* GL_RasterPos2s)(GLshort x, GLshort y);
extern void (APIENTRY* GL_RasterPos2sv)(const GLshort *v);
extern void (APIENTRY* GL_RasterPos3d)(GLdouble x, GLdouble y, GLdouble z);
extern void (APIENTRY* GL_RasterPos3dv)(const GLdouble *v);
extern void (APIENTRY* GL_RasterPos3f)(GLfloat x, GLfloat y, GLfloat z);
extern void (APIENTRY* GL_RasterPos3fv)(const GLfloat *v);
extern void (APIENTRY* GL_RasterPos3i)(GLint x, GLint y, GLint z);
extern void (APIENTRY* GL_RasterPos3iv)(const GLint *v);
extern void (APIENTRY* GL_RasterPos3s)(GLshort x, GLshort y, GLshort z);
extern void (APIENTRY* GL_RasterPos3sv)(const GLshort *v);
extern void (APIENTRY* GL_RasterPos4d)(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
extern void (APIENTRY* GL_RasterPos4dv)(const GLdouble *v);
extern void (APIENTRY* GL_RasterPos4f)(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
extern void (APIENTRY* GL_RasterPos4fv)(const GLfloat *v);
extern void (APIENTRY* GL_RasterPos4i)(GLint x, GLint y, GLint z, GLint w);
extern void (APIENTRY* GL_RasterPos4iv)(const GLint *v);
extern void (APIENTRY* GL_RasterPos4s)(GLshort x, GLshort y, GLshort z, GLshort w);
extern void (APIENTRY* GL_RasterPos4sv)(const GLshort *v);
extern void (APIENTRY* GL_ReadBuffer)(GLenum mode);
extern void (APIENTRY* GL_ReadPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels);
extern void (APIENTRY* GL_Rectd)(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
extern void (APIENTRY* GL_Rectdv)(const GLdouble *v1, const GLdouble *v2);
extern void (APIENTRY* GL_Rectf)(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
extern void (APIENTRY* GL_Rectfv)(const GLfloat *v1, const GLfloat *v2);
extern void (APIENTRY* GL_Recti)(GLint x1, GLint y1, GLint x2, GLint y2);
extern void (APIENTRY* GL_Rectiv)(const GLint *v1, const GLint *v2);
extern void (APIENTRY* GL_Rects)(GLshort x1, GLshort y1, GLshort x2, GLshort y2);
extern void (APIENTRY* GL_Rectsv)(const GLshort *v1, const GLshort *v2);
extern GLint (APIENTRY* GL_RenderMode)(GLenum mode);
extern void (APIENTRY* GL_Rotated)(GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
extern void (APIENTRY* GL_Rotatef)(GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
extern void (APIENTRY* GL_Scaled)(GLdouble x, GLdouble y, GLdouble z);
extern void (APIENTRY* GL_Scalef)(GLfloat x, GLfloat y, GLfloat z);
extern void (APIENTRY* GL_Scissor)(GLint x, GLint y, GLsizei width, GLsizei height);
extern void (APIENTRY* GL_SelectBuffer)(GLsizei size, GLuint *buffer);
extern void (APIENTRY* GL_ShadeModel)(GLenum mode);
extern void (APIENTRY* GL_StencilFunc)(GLenum func, GLint ref, GLuint mask);
extern void (APIENTRY* GL_StencilMask)(GLuint mask);
extern void (APIENTRY* GL_StencilOp)(GLenum fail, GLenum zfail, GLenum zpass);
extern void (APIENTRY* GL_TexCoord1d)(GLdouble s);
extern void (APIENTRY* GL_TexCoord1dv)(const GLdouble *v);
extern void (APIENTRY* GL_TexCoord1f)(GLfloat s);
extern void (APIENTRY* GL_TexCoord1fv)(const GLfloat *v);
extern void (APIENTRY* GL_TexCoord1i)(GLint s);
extern void (APIENTRY* GL_TexCoord1iv)(const GLint *v);
extern void (APIENTRY* GL_TexCoord1s)(GLshort s);
extern void (APIENTRY* GL_TexCoord1sv)(const GLshort *v);
extern void (APIENTRY* GL_TexCoord2d)(GLdouble s, GLdouble t);
extern void (APIENTRY* GL_TexCoord2dv)(const GLdouble *v);
extern void (APIENTRY* GL_TexCoord2f)(GLfloat s, GLfloat t);
extern void (APIENTRY* GL_TexCoord2fv)(const GLfloat *v);
extern void (APIENTRY* GL_TexCoord2i)(GLint s, GLint t);
extern void (APIENTRY* GL_TexCoord2iv)(const GLint *v);
extern void (APIENTRY* GL_TexCoord2s)(GLshort s, GLshort t);
extern void (APIENTRY* GL_TexCoord2sv)(const GLshort *v);
extern void (APIENTRY* GL_TexCoord3d)(GLdouble s, GLdouble t, GLdouble r);
extern void (APIENTRY* GL_TexCoord3dv)(const GLdouble *v);
extern void (APIENTRY* GL_TexCoord3f)(GLfloat s, GLfloat t, GLfloat r);
extern void (APIENTRY* GL_TexCoord3fv)(const GLfloat *v);
extern void (APIENTRY* GL_TexCoord3i)(GLint s, GLint t, GLint r);
extern void (APIENTRY* GL_TexCoord3iv)(const GLint *v);
extern void (APIENTRY* GL_TexCoord3s)(GLshort s, GLshort t, GLshort r);
extern void (APIENTRY* GL_TexCoord3sv)(const GLshort *v);
extern void (APIENTRY* GL_TexCoord4d)(GLdouble s, GLdouble t, GLdouble r, GLdouble q);
extern void (APIENTRY* GL_TexCoord4dv)(const GLdouble *v);
extern void (APIENTRY* GL_TexCoord4f)(GLfloat s, GLfloat t, GLfloat r, GLfloat q);
extern void (APIENTRY* GL_TexCoord4fv)(const GLfloat *v);
extern void (APIENTRY* GL_TexCoord4i)(GLint s, GLint t, GLint r, GLint q);
extern void (APIENTRY* GL_TexCoord4iv)(const GLint *v);
extern void (APIENTRY* GL_TexCoord4s)(GLshort s, GLshort t, GLshort r, GLshort q);
extern void (APIENTRY* GL_TexCoord4sv)(const GLshort *v);
extern void (APIENTRY* GL_TexCoordPointer)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
extern void (APIENTRY* GL_TexEnvf)(GLenum target, GLenum pname, GLfloat param);
extern void (APIENTRY* GL_TexEnvfv)(GLenum target, GLenum pname, const GLfloat *params);
extern void (APIENTRY* GL_TexEnvi)(GLenum target, GLenum pname, GLint param);
extern void (APIENTRY* GL_TexEnviv)(GLenum target, GLenum pname, const GLint *params);
extern void (APIENTRY* GL_TexGend)(GLenum coord, GLenum pname, GLdouble param);
extern void (APIENTRY* GL_TexGendv)(GLenum coord, GLenum pname, const GLdouble *params);
extern void (APIENTRY* GL_TexGenf)(GLenum coord, GLenum pname, GLfloat param);
extern void (APIENTRY* GL_TexGenfv)(GLenum coord, GLenum pname, const GLfloat *params);
extern void (APIENTRY* GL_TexGeni)(GLenum coord, GLenum pname, GLint param);
extern void (APIENTRY* GL_TexGeniv)(GLenum coord, GLenum pname, const GLint *params);
extern void (APIENTRY* GL_TexImage1D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
extern void (APIENTRY* GL_TexImage2D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
extern void (APIENTRY* GL_TexParameterf)(GLenum target, GLenum pname, GLfloat param);
extern void (APIENTRY* GL_TexParameterfv)(GLenum target, GLenum pname, const GLfloat *params);
extern void (APIENTRY* GL_TexParameteri)(GLenum target, GLenum pname, GLint param);
extern void (APIENTRY* GL_TexParameteriv)(GLenum target, GLenum pname, const GLint *params);
extern void (APIENTRY* GL_TexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels);
extern void (APIENTRY* GL_TexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
extern void (APIENTRY* GL_Translated)(GLdouble x, GLdouble y, GLdouble z);
extern void (APIENTRY* GL_Translatef)(GLfloat x, GLfloat y, GLfloat z);
extern void (APIENTRY* GL_Vertex2d)(GLdouble x, GLdouble y);
extern void (APIENTRY* GL_Vertex2dv)(const GLdouble *v);
extern void (APIENTRY* GL_Vertex2f)(GLfloat x, GLfloat y);
extern void (APIENTRY* GL_Vertex2fv)(const GLfloat *v);
extern void (APIENTRY* GL_Vertex2i)(GLint x, GLint y);
extern void (APIENTRY* GL_Vertex2iv)(const GLint *v);
extern void (APIENTRY* GL_Vertex2s)(GLshort x, GLshort y);
extern void (APIENTRY* GL_Vertex2sv)(const GLshort *v);
extern void (APIENTRY* GL_Vertex3d)(GLdouble x, GLdouble y, GLdouble z);
extern void (APIENTRY* GL_Vertex3dv)(const GLdouble *v);
extern void (APIENTRY* GL_Vertex3f)(GLfloat x, GLfloat y, GLfloat z);
extern void (APIENTRY* GL_Vertex3fv)(const GLfloat *v);
extern void (APIENTRY* GL_Vertex3i)(GLint x, GLint y, GLint z);
extern void (APIENTRY* GL_Vertex3iv)(const GLint *v);
extern void (APIENTRY* GL_Vertex3s)(GLshort x, GLshort y, GLshort z);
extern void (APIENTRY* GL_Vertex3sv)(const GLshort *v);
extern void (APIENTRY* GL_Vertex4d)(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
extern void (APIENTRY* GL_Vertex4dv)(const GLdouble *v);
extern void (APIENTRY* GL_Vertex4f)(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
extern void (APIENTRY* GL_Vertex4fv)(const GLfloat *v);
extern void (APIENTRY* GL_Vertex4i)(GLint x, GLint y, GLint z, GLint w);
extern void (APIENTRY* GL_Vertex4iv)(const GLint *v);
extern void (APIENTRY* GL_Vertex4s)(GLshort x, GLshort y, GLshort z, GLshort w);
extern void (APIENTRY* GL_Vertex4sv)(const GLshort *v);
extern void (APIENTRY* GL_VertexPointer)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
extern void (APIENTRY* GL_Viewport)(GLint x, GLint y, GLsizei width, GLsizei height);

void GL_Load(void);
